<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * times サービス化。
 *
 * 1. 旧ブログの記事（posts / post_tags）を archived_posts / archived_post_tags に移す。
 *    テーブルをリネームしても主キーのインデックス名やシーケンス名は元のまま残り、
 *    新しい posts テーブルの posts_pkey などと衝突するため、それらも合わせてリネームする。
 * 2. times の投稿・ユーザー・リアクション・フォロー・通知・セッションのテーブルを作る。
 */
final class Version20260923000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '旧記事を archived_posts に移し、times のテーブルを作成する';
    }

    public function up(Schema $schema): void
    {
        // ---------- 旧記事をアーカイブへ ----------
        $this->addSql('ALTER TABLE posts RENAME TO archived_posts');
        $this->addSql('ALTER INDEX posts_pkey RENAME TO archived_posts_pkey');
        $this->addSql('ALTER SEQUENCE posts_id_seq RENAME TO archived_posts_id_seq');
        $this->addSql('ALTER INDEX uniq_885dbafa989d9b62 RENAME TO UNIQ_5504B3DB989D9B62');
        $this->addSql('ALTER INDEX idx_posts_published RENAME TO idx_archived_posts_published');

        $this->addSql('ALTER TABLE post_tags RENAME TO archived_post_tags');
        $this->addSql('ALTER INDEX post_tags_pkey RENAME TO archived_post_tags_pkey');
        $this->addSql('ALTER TABLE archived_post_tags RENAME COLUMN post_id TO archived_post_id');
        $this->addSql('ALTER TABLE archived_post_tags RENAME CONSTRAINT fk_a6e9f32d4b89032c TO FK_22AD488DBECA7332');
        $this->addSql('ALTER TABLE archived_post_tags RENAME CONSTRAINT fk_a6e9f32dbad26311 TO FK_22AD488DBAD26311');
        $this->addSql('ALTER INDEX idx_a6e9f32d4b89032c RENAME TO IDX_22AD488DBECA7332');
        $this->addSql('ALTER INDEX idx_a6e9f32dbad26311 RENAME TO IDX_22AD488DBAD26311');

        // ---------- users ----------
        $this->addSql('CREATE TABLE users (id UUID NOT NULL, google_sub VARCHAR(255) DEFAULT NULL, handle VARCHAR(32) DEFAULT NULL, display_name VARCHAR(50) NOT NULL, avatar_url VARCHAR(1024) DEFAULT NULL, bio VARCHAR(300) DEFAULT NULL, company_name VARCHAR(100) DEFAULT NULL, company_slug VARCHAR(100) DEFAULT NULL, role VARCHAR(16) NOT NULL, suspended_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E788A50 ON users (google_sub)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9918020D9 ON users (handle)');
        $this->addSql('CREATE INDEX idx_users_company ON users (company_slug)');

        // ---------- posts ----------
        $this->addSql('CREATE TABLE posts (id UUID NOT NULL, body_markdown TEXT NOT NULL, body_html TEXT NOT NULL, image_key VARCHAR(128) DEFAULT NULL, reply_count INT DEFAULT 0 NOT NULL, reaction_count INT DEFAULT 0 NOT NULL, last_reply_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, edited_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, hidden_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, author_id UUID NOT NULL, parent_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_885DBAFAF675F31B ON posts (author_id)');
        $this->addSql('CREATE INDEX IDX_885DBAFA727ACA70 ON posts (parent_id)');
        $this->addSql('CREATE INDEX idx_posts_room ON posts (author_id, id) WHERE (parent_id IS NULL)');
        $this->addSql('CREATE INDEX idx_posts_lobby ON posts (id) WHERE (parent_id IS NULL)');
        $this->addSql('CREATE INDEX idx_posts_thread ON posts (parent_id, id)');
        $this->addSql('ALTER TABLE posts ADD CONSTRAINT FK_885DBAFAF675F31B FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE posts ADD CONSTRAINT FK_885DBAFA727ACA70 FOREIGN KEY (parent_id) REFERENCES posts (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql('CREATE TABLE post_tags (post_id UUID NOT NULL, tag_id INT NOT NULL, PRIMARY KEY (post_id, tag_id))');
        $this->addSql('CREATE INDEX IDX_A6E9F32D4B89032C ON post_tags (post_id)');
        $this->addSql('CREATE INDEX IDX_A6E9F32DBAD26311 ON post_tags (tag_id)');
        $this->addSql('ALTER TABLE post_tags ADD CONSTRAINT FK_A6E9F32D4B89032C FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE post_tags ADD CONSTRAINT FK_A6E9F32DBAD26311 FOREIGN KEY (tag_id) REFERENCES tags (id) ON DELETE CASCADE');

        // ---------- reactions ----------
        $this->addSql('CREATE TABLE reactions (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, emoji VARCHAR(32) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, post_id UUID NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_38737FB34B89032C ON reactions (post_id)');
        $this->addSql('CREATE INDEX IDX_38737FB3A76ED395 ON reactions (user_id)');
        $this->addSql('CREATE INDEX idx_reactions_created ON reactions (created_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_reactions_post_user_emoji ON reactions (post_id, user_id, emoji)');
        $this->addSql('ALTER TABLE reactions ADD CONSTRAINT FK_38737FB34B89032C FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reactions ADD CONSTRAINT FK_38737FB3A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');

        // ---------- follows ----------
        $this->addSql('CREATE TABLE follows (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, last_read_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, follower_id UUID NOT NULL, followee_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4B638A73AC24F853 ON follows (follower_id)');
        $this->addSql('CREATE INDEX IDX_4B638A7361EA9775 ON follows (followee_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_follows_pair ON follows (follower_id, followee_id)');
        $this->addSql('ALTER TABLE follows ADD CONSTRAINT FK_4B638A73AC24F853 FOREIGN KEY (follower_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE follows ADD CONSTRAINT FK_4B638A7361EA9775 FOREIGN KEY (followee_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');

        // ---------- notifications ----------
        $this->addSql('CREATE TABLE notifications (id UUID NOT NULL, type VARCHAR(16) NOT NULL, read_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id UUID NOT NULL, actor_id UUID NOT NULL, post_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6000B0D3A76ED395 ON notifications (user_id)');
        $this->addSql('CREATE INDEX IDX_6000B0D310DAF24A ON notifications (actor_id)');
        $this->addSql('CREATE INDEX IDX_6000B0D34B89032C ON notifications (post_id)');
        $this->addSql('CREATE INDEX idx_notifications_user ON notifications (user_id, id)');
        $this->addSql('CREATE INDEX idx_notifications_unread ON notifications (user_id) WHERE (read_at IS NULL)');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D3A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D310DAF24A FOREIGN KEY (actor_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D34B89032C FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE NOT DEFERRABLE');

        // ---------- sessions ----------
        $this->addSql('CREATE TABLE sessions (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token_hash VARCHAR(64) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9A609D13B3BC57DA ON sessions (token_hash)');
        $this->addSql('CREATE INDEX IDX_9A609D13A76ED395 ON sessions (user_id)');
        $this->addSql('ALTER TABLE sessions ADD CONSTRAINT FK_9A609D13A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE sessions');
        $this->addSql('DROP TABLE notifications');
        $this->addSql('DROP TABLE follows');
        $this->addSql('DROP TABLE reactions');
        $this->addSql('DROP TABLE post_tags');
        $this->addSql('DROP TABLE posts');
        $this->addSql('DROP TABLE users');

        $this->addSql('ALTER INDEX IDX_22AD488DBAD26311 RENAME TO idx_a6e9f32dbad26311');
        $this->addSql('ALTER INDEX IDX_22AD488DBECA7332 RENAME TO idx_a6e9f32d4b89032c');
        $this->addSql('ALTER TABLE archived_post_tags RENAME CONSTRAINT FK_22AD488DBAD26311 TO fk_a6e9f32dbad26311');
        $this->addSql('ALTER TABLE archived_post_tags RENAME CONSTRAINT FK_22AD488DBECA7332 TO fk_a6e9f32d4b89032c');
        $this->addSql('ALTER TABLE archived_post_tags RENAME COLUMN archived_post_id TO post_id');
        $this->addSql('ALTER INDEX archived_post_tags_pkey RENAME TO post_tags_pkey');
        $this->addSql('ALTER TABLE archived_post_tags RENAME TO post_tags');

        $this->addSql('ALTER INDEX idx_archived_posts_published RENAME TO idx_posts_published');
        $this->addSql('ALTER INDEX UNIQ_5504B3DB989D9B62 RENAME TO uniq_885dbafa989d9b62');
        $this->addSql('ALTER SEQUENCE archived_posts_id_seq RENAME TO posts_id_seq');
        $this->addSql('ALTER INDEX archived_posts_pkey RENAME TO posts_pkey');
        $this->addSql('ALTER TABLE archived_posts RENAME TO posts');
    }
}
