<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * 荒らし対策の最低限。
 *
 * - blocks: ブロック
 * - reports: 投稿の通報
 * - cache_items: レート制限の状態（Symfony Cache の DoctrineDbalAdapter が使う）
 */
final class Version20260923040731 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'ブロック・通報・レート制限用のテーブルを作成する';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE blocks (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, blocker_id UUID NOT NULL, blocked_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CEED9578548D5975 ON blocks (blocker_id)');
        $this->addSql('CREATE INDEX IDX_CEED957821FF5136 ON blocks (blocked_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_blocks_pair ON blocks (blocker_id, blocked_id)');
        $this->addSql('CREATE TABLE reports (id UUID NOT NULL, reason VARCHAR(16) NOT NULL, detail VARCHAR(500) DEFAULT NULL, resolution VARCHAR(16) DEFAULT NULL, resolved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, post_id UUID NOT NULL, reporter_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F11FA7454B89032C ON reports (post_id)');
        $this->addSql('CREATE INDEX IDX_F11FA745E1CFE6F5 ON reports (reporter_id)');
        $this->addSql('CREATE INDEX idx_reports_open ON reports (id) WHERE (resolved_at IS NULL)');
        $this->addSql('CREATE UNIQUE INDEX uniq_reports_post_reporter ON reports (post_id, reporter_id)');
        $this->addSql('CREATE TABLE cache_items (item_id VARCHAR(255) NOT NULL, item_data BYTEA NOT NULL, item_lifetime INT DEFAULT NULL, item_time INT NOT NULL, PRIMARY KEY (item_id))');
        $this->addSql('ALTER TABLE blocks ADD CONSTRAINT FK_CEED9578548D5975 FOREIGN KEY (blocker_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE blocks ADD CONSTRAINT FK_CEED957821FF5136 FOREIGN KEY (blocked_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reports ADD CONSTRAINT FK_F11FA7454B89032C FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reports ADD CONSTRAINT FK_F11FA745E1CFE6F5 FOREIGN KEY (reporter_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE blocks DROP CONSTRAINT FK_CEED9578548D5975');
        $this->addSql('ALTER TABLE blocks DROP CONSTRAINT FK_CEED957821FF5136');
        $this->addSql('ALTER TABLE reports DROP CONSTRAINT FK_F11FA7454B89032C');
        $this->addSql('ALTER TABLE reports DROP CONSTRAINT FK_F11FA745E1CFE6F5');
        $this->addSql('DROP TABLE blocks');
        $this->addSql('DROP TABLE reports');
        $this->addSql('DROP TABLE cache_items');
    }
}
