/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PostsIndexRouteImport } from './routes/posts.index'
import { Route as PostsSlugRouteImport } from './routes/posts.$slug'
import { Route as TagsIndexRouteImport } from './routes/tags.index'
import { Route as TagsSlugRouteImport } from './routes/tags.$slug'
import { Route as UploadsKeyRouteImport } from './routes/uploads.$key'
import { Route as AdminPostsNewRouteImport } from './routes/admin.posts.new'
import { Route as AdminPostsIdEditRouteImport } from './routes/admin.posts.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsIndexRoute = TagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsSlugRoute = TagsSlugRouteImport.update({
  id: '/tags/$slug',
  path: '/tags/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadsKeyRoute = UploadsKeyRouteImport.update({
  id: '/uploads/$key',
  path: '/uploads/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsNewRoute = AdminPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsIdEditRoute = AdminPostsIdEditRouteImport.update({
  id: '/posts/$id/edit',
  path: '/posts/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/tags/$slug': typeof TagsSlugRoute
  '/uploads/$key': typeof UploadsKeyRoute
  '/admin/': typeof AdminIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/tags/': typeof TagsIndexRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/posts/$id/edit': typeof AdminPostsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/tags/$slug': typeof TagsSlugRoute
  '/uploads/$key': typeof UploadsKeyRoute
  '/admin': typeof AdminIndexRoute
  '/posts': typeof PostsIndexRoute
  '/tags': typeof TagsIndexRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/posts/$id/edit': typeof AdminPostsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/tags/$slug': typeof TagsSlugRoute
  '/uploads/$key': typeof UploadsKeyRoute
  '/admin/': typeof AdminIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/tags/': typeof TagsIndexRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/posts/$id/edit': typeof AdminPostsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/robots.txt'
    | '/rss.xml'
    | '/posts/$slug'
    | '/tags/$slug'
    | '/uploads/$key'
    | '/admin/'
    | '/posts/'
    | '/tags/'
    | '/admin/posts/new'
    | '/admin/posts/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/robots.txt'
    | '/rss.xml'
    | '/posts/$slug'
    | '/tags/$slug'
    | '/uploads/$key'
    | '/admin'
    | '/posts'
    | '/tags'
    | '/admin/posts/new'
    | '/admin/posts/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/robots.txt'
    | '/rss.xml'
    | '/posts/$slug'
    | '/tags/$slug'
    | '/uploads/$key'
    | '/admin/'
    | '/posts/'
    | '/tags/'
    | '/admin/posts/new'
    | '/admin/posts/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  PostsSlugRoute: typeof PostsSlugRoute
  TagsSlugRoute: typeof TagsSlugRoute
  UploadsKeyRoute: typeof UploadsKeyRoute
  PostsIndexRoute: typeof PostsIndexRoute
  TagsIndexRoute: typeof TagsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$slug': {
      id: '/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/': {
      id: '/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof TagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/$slug': {
      id: '/tags/$slug'
      path: '/tags/$slug'
      fullPath: '/tags/$slug'
      preLoaderRoute: typeof TagsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uploads/$key': {
      id: '/uploads/$key'
      path: '/uploads/$key'
      fullPath: '/uploads/$key'
      preLoaderRoute: typeof UploadsKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts/new': {
      id: '/admin/posts/new'
      path: '/posts/new'
      fullPath: '/admin/posts/new'
      preLoaderRoute: typeof AdminPostsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts/$id/edit': {
      id: '/admin/posts/$id/edit'
      path: '/posts/$id/edit'
      fullPath: '/admin/posts/$id/edit'
      preLoaderRoute: typeof AdminPostsIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPostsNewRoute: typeof AdminPostsNewRoute
  AdminPostsIdEditRoute: typeof AdminPostsIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminPostsNewRoute: AdminPostsNewRoute,
  AdminPostsIdEditRoute: AdminPostsIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  PostsSlugRoute: PostsSlugRoute,
  TagsSlugRoute: TagsSlugRoute,
  UploadsKeyRoute: UploadsKeyRoute,
  PostsIndexRoute: PostsIndexRoute,
  TagsIndexRoute: TagsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
