/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DevLoginRouteImport } from './routes/dev-login'
import { Route as FollowingRouteImport } from './routes/following'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AtChar123handleChar125IndexRouteImport } from './routes/@{$handle}.index'
import { Route as AtChar123handleChar125PostIdRouteImport } from './routes/@{$handle}.$postId'
import { Route as AtChar123handleChar125RssDotxmlRouteImport } from './routes/@{$handle}.rss[.]xml'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminArticlesRouteImport } from './routes/admin.articles'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminTagsRouteImport } from './routes/admin.tags'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as ArticlesNewRouteImport } from './routes/articles.new'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthGoogleRouteImport } from './routes/auth.google'
import { Route as OrgCompanySlugRouteImport } from './routes/org.$companySlug'
import { Route as PostsIndexRouteImport } from './routes/posts.index'
import { Route as PostsSlugRouteImport } from './routes/posts.$slug'
import { Route as TagsIndexRouteImport } from './routes/tags.index'
import { Route as TagsSlugRouteImport } from './routes/tags.$slug'
import { Route as UploadsKeyRouteImport } from './routes/uploads.$key'
import { Route as AtChar123handleChar125ArticlesIndexRouteImport } from './routes/@{$handle}.articles.index'
import { Route as AtChar123handleChar125ArticlesSlugRouteImport } from './routes/@{$handle}.articles.$slug'
import { Route as ArticlesIdEditRouteImport } from './routes/articles.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DevLoginRoute = DevLoginRouteImport.update({
  id: '/dev-login',
  path: '/dev-login',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowingRoute = FollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AtChar123handleChar125IndexRoute =
  AtChar123handleChar125IndexRouteImport.update({
    id: '/@{$handle}/',
    path: '/@{$handle}/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AtChar123handleChar125PostIdRoute =
  AtChar123handleChar125PostIdRouteImport.update({
    id: '/@{$handle}/$postId',
    path: '/@{$handle}/$postId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AtChar123handleChar125RssDotxmlRoute =
  AtChar123handleChar125RssDotxmlRouteImport.update({
    id: '/@{$handle}/rss.xml',
    path: '/@{$handle}/rss.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesRoute = AdminArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTagsRoute = AdminTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesNewRoute = ArticlesNewRouteImport.update({
  id: '/articles/new',
  path: '/articles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleRoute = AuthGoogleRouteImport.update({
  id: '/auth/google',
  path: '/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgCompanySlugRoute = OrgCompanySlugRouteImport.update({
  id: '/org/$companySlug',
  path: '/org/$companySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsIndexRoute = TagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsSlugRoute = TagsSlugRouteImport.update({
  id: '/tags/$slug',
  path: '/tags/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadsKeyRoute = UploadsKeyRouteImport.update({
  id: '/uploads/$key',
  path: '/uploads/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const AtChar123handleChar125ArticlesIndexRoute =
  AtChar123handleChar125ArticlesIndexRouteImport.update({
    id: '/@{$handle}/articles/',
    path: '/@{$handle}/articles/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AtChar123handleChar125ArticlesSlugRoute =
  AtChar123handleChar125ArticlesSlugRouteImport.update({
    id: '/@{$handle}/articles/$slug',
    path: '/@{$handle}/articles/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ArticlesIdEditRoute = ArticlesIdEditRouteImport.update({
  id: '/articles/$id/edit',
  path: '/articles/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/dev-login': typeof DevLoginRoute
  '/following': typeof FollowingRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/welcome': typeof WelcomeRoute
  '/@{$handle}/$postId': typeof AtChar123handleChar125PostIdRoute
  '/@{$handle}/rss.xml': typeof AtChar123handleChar125RssDotxmlRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/users': typeof AdminUsersRoute
  '/articles/new': typeof ArticlesNewRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/google': typeof AuthGoogleRoute
  '/org/$companySlug': typeof OrgCompanySlugRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/tags/$slug': typeof TagsSlugRoute
  '/uploads/$key': typeof UploadsKeyRoute
  '/@{$handle}/': typeof AtChar123handleChar125IndexRoute
  '/admin/': typeof AdminIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/tags/': typeof TagsIndexRoute
  '/@{$handle}/articles/$slug': typeof AtChar123handleChar125ArticlesSlugRoute
  '/articles/$id/edit': typeof ArticlesIdEditRoute
  '/@{$handle}/articles/': typeof AtChar123handleChar125ArticlesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dev-login': typeof DevLoginRoute
  '/following': typeof FollowingRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/welcome': typeof WelcomeRoute
  '/@{$handle}/$postId': typeof AtChar123handleChar125PostIdRoute
  '/@{$handle}/rss.xml': typeof AtChar123handleChar125RssDotxmlRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/users': typeof AdminUsersRoute
  '/articles/new': typeof ArticlesNewRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/google': typeof AuthGoogleRoute
  '/org/$companySlug': typeof OrgCompanySlugRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/tags/$slug': typeof TagsSlugRoute
  '/uploads/$key': typeof UploadsKeyRoute
  '/@{$handle}': typeof AtChar123handleChar125IndexRoute
  '/admin': typeof AdminIndexRoute
  '/articles': typeof ArticlesIndexRoute
  '/posts': typeof PostsIndexRoute
  '/tags': typeof TagsIndexRoute
  '/@{$handle}/articles/$slug': typeof AtChar123handleChar125ArticlesSlugRoute
  '/articles/$id/edit': typeof ArticlesIdEditRoute
  '/@{$handle}/articles': typeof AtChar123handleChar125ArticlesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/dev-login': typeof DevLoginRoute
  '/following': typeof FollowingRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/welcome': typeof WelcomeRoute
  '/@{$handle}/$postId': typeof AtChar123handleChar125PostIdRoute
  '/@{$handle}/rss.xml': typeof AtChar123handleChar125RssDotxmlRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/users': typeof AdminUsersRoute
  '/articles/new': typeof ArticlesNewRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/google': typeof AuthGoogleRoute
  '/org/$companySlug': typeof OrgCompanySlugRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/tags/$slug': typeof TagsSlugRoute
  '/uploads/$key': typeof UploadsKeyRoute
  '/@{$handle}/': typeof AtChar123handleChar125IndexRoute
  '/admin/': typeof AdminIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/tags/': typeof TagsIndexRoute
  '/@{$handle}/articles/$slug': typeof AtChar123handleChar125ArticlesSlugRoute
  '/articles/$id/edit': typeof ArticlesIdEditRoute
  '/@{$handle}/articles/': typeof AtChar123handleChar125ArticlesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/dev-login'
    | '/following'
    | '/login'
    | '/notifications'
    | '/robots.txt'
    | '/rss.xml'
    | '/search'
    | '/settings'
    | '/welcome'
    | '/@{$handle}/$postId'
    | '/@{$handle}/rss.xml'
    | '/admin/articles'
    | '/admin/reports'
    | '/admin/tags'
    | '/admin/users'
    | '/articles/new'
    | '/auth/callback'
    | '/auth/google'
    | '/org/$companySlug'
    | '/posts/$slug'
    | '/tags/$slug'
    | '/uploads/$key'
    | '/@{$handle}/'
    | '/admin/'
    | '/articles/'
    | '/posts/'
    | '/tags/'
    | '/@{$handle}/articles/$slug'
    | '/articles/$id/edit'
    | '/@{$handle}/articles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dev-login'
    | '/following'
    | '/login'
    | '/notifications'
    | '/robots.txt'
    | '/rss.xml'
    | '/search'
    | '/settings'
    | '/welcome'
    | '/@{$handle}/$postId'
    | '/@{$handle}/rss.xml'
    | '/admin/articles'
    | '/admin/reports'
    | '/admin/tags'
    | '/admin/users'
    | '/articles/new'
    | '/auth/callback'
    | '/auth/google'
    | '/org/$companySlug'
    | '/posts/$slug'
    | '/tags/$slug'
    | '/uploads/$key'
    | '/@{$handle}'
    | '/admin'
    | '/articles'
    | '/posts'
    | '/tags'
    | '/@{$handle}/articles/$slug'
    | '/articles/$id/edit'
    | '/@{$handle}/articles'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/dev-login'
    | '/following'
    | '/login'
    | '/notifications'
    | '/robots.txt'
    | '/rss.xml'
    | '/search'
    | '/settings'
    | '/welcome'
    | '/@{$handle}/$postId'
    | '/@{$handle}/rss.xml'
    | '/admin/articles'
    | '/admin/reports'
    | '/admin/tags'
    | '/admin/users'
    | '/articles/new'
    | '/auth/callback'
    | '/auth/google'
    | '/org/$companySlug'
    | '/posts/$slug'
    | '/tags/$slug'
    | '/uploads/$key'
    | '/@{$handle}/'
    | '/admin/'
    | '/articles/'
    | '/posts/'
    | '/tags/'
    | '/@{$handle}/articles/$slug'
    | '/articles/$id/edit'
    | '/@{$handle}/articles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  DevLoginRoute: typeof DevLoginRoute
  FollowingRoute: typeof FollowingRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  WelcomeRoute: typeof WelcomeRoute
  AtChar123handleChar125PostIdRoute: typeof AtChar123handleChar125PostIdRoute
  AtChar123handleChar125RssDotxmlRoute: typeof AtChar123handleChar125RssDotxmlRoute
  ArticlesNewRoute: typeof ArticlesNewRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthGoogleRoute: typeof AuthGoogleRoute
  OrgCompanySlugRoute: typeof OrgCompanySlugRoute
  PostsSlugRoute: typeof PostsSlugRoute
  TagsSlugRoute: typeof TagsSlugRoute
  UploadsKeyRoute: typeof UploadsKeyRoute
  AtChar123handleChar125IndexRoute: typeof AtChar123handleChar125IndexRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  PostsIndexRoute: typeof PostsIndexRoute
  TagsIndexRoute: typeof TagsIndexRoute
  AtChar123handleChar125ArticlesSlugRoute: typeof AtChar123handleChar125ArticlesSlugRoute
  ArticlesIdEditRoute: typeof ArticlesIdEditRoute
  AtChar123handleChar125ArticlesIndexRoute: typeof AtChar123handleChar125ArticlesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-login': {
      id: '/dev-login'
      path: '/dev-login'
      fullPath: '/dev-login'
      preLoaderRoute: typeof DevLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/following': {
      id: '/following'
      path: '/following'
      fullPath: '/following'
      preLoaderRoute: typeof FollowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/@{$handle}/': {
      id: '/@{$handle}/'
      path: '/@{$handle}'
      fullPath: '/@{$handle}/'
      preLoaderRoute: typeof AtChar123handleChar125IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/@{$handle}/$postId': {
      id: '/@{$handle}/$postId'
      path: '/@{$handle}/$postId'
      fullPath: '/@{$handle}/$postId'
      preLoaderRoute: typeof AtChar123handleChar125PostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/@{$handle}/rss.xml': {
      id: '/@{$handle}/rss.xml'
      path: '/@{$handle}/rss.xml'
      fullPath: '/@{$handle}/rss.xml'
      preLoaderRoute: typeof AtChar123handleChar125RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles': {
      id: '/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminArticlesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tags': {
      id: '/admin/tags'
      path: '/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AdminTagsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/new': {
      id: '/articles/new'
      path: '/articles/new'
      fullPath: '/articles/new'
      preLoaderRoute: typeof ArticlesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google': {
      id: '/auth/google'
      path: '/auth/google'
      fullPath: '/auth/google'
      preLoaderRoute: typeof AuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$companySlug': {
      id: '/org/$companySlug'
      path: '/org/$companySlug'
      fullPath: '/org/$companySlug'
      preLoaderRoute: typeof OrgCompanySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$slug': {
      id: '/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/': {
      id: '/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof TagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/$slug': {
      id: '/tags/$slug'
      path: '/tags/$slug'
      fullPath: '/tags/$slug'
      preLoaderRoute: typeof TagsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uploads/$key': {
      id: '/uploads/$key'
      path: '/uploads/$key'
      fullPath: '/uploads/$key'
      preLoaderRoute: typeof UploadsKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/@{$handle}/articles/': {
      id: '/@{$handle}/articles/'
      path: '/@{$handle}/articles'
      fullPath: '/@{$handle}/articles/'
      preLoaderRoute: typeof AtChar123handleChar125ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/@{$handle}/articles/$slug': {
      id: '/@{$handle}/articles/$slug'
      path: '/@{$handle}/articles/$slug'
      fullPath: '/@{$handle}/articles/$slug'
      preLoaderRoute: typeof AtChar123handleChar125ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$id/edit': {
      id: '/articles/$id/edit'
      path: '/articles/$id/edit'
      fullPath: '/articles/$id/edit'
      preLoaderRoute: typeof ArticlesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminArticlesRoute: typeof AdminArticlesRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminTagsRoute: typeof AdminTagsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminArticlesRoute: AdminArticlesRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminTagsRoute: AdminTagsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  DevLoginRoute: DevLoginRoute,
  FollowingRoute: FollowingRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  WelcomeRoute: WelcomeRoute,
  AtChar123handleChar125PostIdRoute: AtChar123handleChar125PostIdRoute,
  AtChar123handleChar125RssDotxmlRoute: AtChar123handleChar125RssDotxmlRoute,
  ArticlesNewRoute: ArticlesNewRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthGoogleRoute: AuthGoogleRoute,
  OrgCompanySlugRoute: OrgCompanySlugRoute,
  PostsSlugRoute: PostsSlugRoute,
  TagsSlugRoute: TagsSlugRoute,
  UploadsKeyRoute: UploadsKeyRoute,
  AtChar123handleChar125IndexRoute: AtChar123handleChar125IndexRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  PostsIndexRoute: PostsIndexRoute,
  TagsIndexRoute: TagsIndexRoute,
  AtChar123handleChar125ArticlesSlugRoute:
    AtChar123handleChar125ArticlesSlugRoute,
  ArticlesIdEditRoute: ArticlesIdEditRoute,
  AtChar123handleChar125ArticlesIndexRoute:
    AtChar123handleChar125ArticlesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
