/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_admin_posts_index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/posts/moderate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 未判定の投稿を Jev でまとめて判定する（1回に最大 20 件）。remaining が 0 になるまで繰り返し呼ぶ。TYPESAFE_API_KEY が未設定なら 422 */
        post: operations["post_api_admin_posts_moderate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/posts/{id}/hide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_admin_posts_hide"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/posts/{id}/unhide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_admin_posts_unhide"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/posts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_api_admin_posts_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_admin_users_index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{id}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_admin_users_suspend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{id}/unsuspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_admin_users_unsuspend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_admin_reports_index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/reports/{id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_admin_reports_dismiss"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_admin_tags_index"];
        put?: never;
        post: operations["post_api_admin_tags_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/archive/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_archive_posts_index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/archive/posts/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_archive_posts_show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/archive/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_archive_tags_index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_auth_google_authorize"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_auth_google_callback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/email/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** メールアドレスとパスワードで新規登録し、そのままログインする。確認メールは送らない。 */
        post: operations["post_api_auth_email_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/email/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** メールアドレスとパスワードでログインする。 */
        post: operations["post_api_auth_email_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_api_auth_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/dev-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 開発用のログイン。Google の設定なしでローカルの動作確認をするためだけに使う。
         *     APP_ENV=dev かつ DEV_LOGIN_ENABLED=1 のときしか動かない。
         */
        post: operations["post_api_auth_dev_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blocks/{handle}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["put_api_blocks_put"];
        post?: never;
        delete: operations["delete_api_blocks_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_blocks_index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/follows/{handle}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["put_api_follows_put"];
        post?: never;
        delete: operations["delete_api_follows_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/follows/{handle}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_follows_read"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/following": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_following"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lobby": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_lobby"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/popular": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_rooms_popular"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_me_show"];
        put: operations["put_api_me_update"];
        post?: never;
        delete: operations["delete_api_me_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 画像アップロードの枠を1つ使う。R2 には API から触れないので、Worker は
         *     これが 200 を返したときだけ R2 に置く（連続アップロードで無料枠を削らせないため）。
         */
        post: operations["post_api_me_uploads"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/viewer-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_me_viewer_state"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_notifications_index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_notifications_read"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs/{slug}/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_orgs_users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_posts_show"];
        put: operations["put_api_posts_update"];
        post?: never;
        delete: operations["delete_api_posts_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/{id}/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_posts_source"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_posts_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/{id}/reactions/{emoji}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["put_api_reactions_put"];
        post?: never;
        delete: operations["delete_api_reactions_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/{id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_posts_report"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_tags_index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags/{slug}/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_tags_posts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{handle}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_users_show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{handle}/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_users_posts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{handle}/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_users_articles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{handle}/articles/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_users_articles_show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_me_articles"];
        put?: never;
        post: operations["post_api_me_articles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/articles/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_me_articles_preview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/articles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_me_articles_show"];
        put: operations["put_api_me_articles_update"];
        post?: never;
        delete: operations["delete_api_me_articles_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_admin_articles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/articles/{id}/hide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_admin_articles_hide"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/articles/{id}/unhide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_admin_articles_unhide"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/articles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_api_admin_articles_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        TagInput: {
            /**
             * 表示名。日本語も使える。
             * @default
             * @example JavaScript
             */
            name: string;
            /**
             * URL に使う識別子。日本語名から機械的に導出できないため明示的に指定する。
             * @default
             * @example javascript
             */
            slug: string;
        };
        OAuthCallbackInput: {
            /** @default  */
            code: string;
        };
        EmailCredentialsInput: {
            email: string;
            password: string;
        };
        DevLoginInput: {
            /**
             * @description ログインする（なければ作る）ユーザーの handle
             * @default
             * @example alice
             */
            handle: string;
        };
        MeUpdateInput: {
            /**
             * @description 初回のみ。英小文字・数字・_ の 3〜20 文字
             * @example alice
             */
            handle?: string | null;
            /** @default  */
            displayName: string;
            bio?: string | null;
            /** @description 自己申告の所属。空なら未設定 */
            companyName?: string | null;
        };
        PostInput: {
            /**
             * @description Markdown
             * @default
             * @example 今日は **OpenAPI** の型生成を試した
             *
             *     https://example.com
             */
            bodyMarkdown: string;
            /** @description 返信先の親投稿 ID */
            parentId?: string | null;
            /**
             * Worker が R2 に置いた画像のキー。投稿者本人のアップロードしか指定できない。
             * @description R2 に置いた画像のキー（1枚まで）
             */
            imageKey?: string | null;
            /**
             * @description 既存タグの slug。返信には付けられない
             * @default []
             * @example [
             *       "php"
             *     ]
             */
            tagSlugs: string[];
            /**
             * @description 新しく作るタグの名前（既にあればそのタグを使う）。tagSlugs と合わせて 3 個まで
             * @default []
             * @example [
             *       "朝活"
             *     ]
             */
            newTags: string[];
            /** @description 添付する公開中のブログ記事の ID */
            articleId?: number | null;
        };
        PostUpdateInput: {
            /**
             * @description Markdown
             * @default
             */
            bodyMarkdown: string;
            /** @default [] */
            tagSlugs: string[];
            /**
             * @description 新しく作るタグの名前（既にあればそのタグを使う）。tagSlugs と合わせて 3 個まで
             * @default []
             * @example [
             *       "朝活"
             *     ]
             */
            newTags: string[];
        };
        /** @enum {string} */
        ReportReason: "spam" | "harassment" | "privacy" | "illegal" | "other";
        ReportInput: {
            reason?: components["schemas"]["ReportReason"];
            /** @description 詳細（任意） */
            detail?: string | null;
        };
        AdminUser: {
            id: string;
            handle?: string | null;
            displayName: string;
            avatarUrl?: string | null;
            /** @enum {string} */
            role: "user" | "admin";
            /** Format: date-time */
            suspendedAt?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        AdminPost: {
            id: string;
            parentId?: string | null;
            author: components["schemas"]["AdminUser"];
            bodyMarkdown: string;
            imageKey?: string | null;
            /** Format: date-time */
            hiddenAt?: string | null;
            /**
             * @description Jev の判定。null は問題なし・未判定
             * @enum {string|null}
             */
            moderation?: "sensitive" | "blocked" | null;
            /** @description 最も確率が高かったカテゴリ（sexual / violence / harassment / legal）。未判定なら null */
            moderationCategory?: string | null;
            /** @description そのカテゴリの確率（0〜1）。未判定なら null */
            moderationScore?: number | null;
            /** Format: date-time */
            createdAt: string;
        };
        AdminPostPage: {
            items: components["schemas"]["AdminPost"][];
            nextCursor?: string | null;
        };
        PostDeleted: {
            /** @description 消えた画像のキー */
            imageKey?: string | null;
        };
        ValidationError: {
            /** @example 入力内容に誤りがあります。 */
            message: string;
            /**
             * @example {
             *       "slug": "slug は必須です。"
             *     }
             */
            errors: {
                [key: string]: string;
            };
        };
        AdminReport: {
            id: string;
            post: components["schemas"]["AdminPost"];
            /**
             * @description 投稿の状態
             * @enum {string}
             */
            postState: "visible" | "hidden" | "deleted";
            reporter: components["schemas"]["AdminUser"];
            /** @enum {string} */
            reason: "spam" | "harassment" | "privacy" | "illegal" | "other";
            detail?: string | null;
            /** @enum {string|null} */
            resolution?: "actioned" | "dismissed" | null;
            resolvedAt?: string | null;
            createdAt: string;
        };
        AdminReportPage: {
            items: components["schemas"]["AdminReport"][];
            nextCursor?: string | null;
            /** @description 未対応の通報の総数 */
            openCount: number;
        };
        TagSummary: {
            /** @example JavaScript */
            name: string;
            /** @example javascript */
            slug: string;
        };
        ArchivedPostSummary: {
            id: number;
            /** @example hello-world */
            slug: string;
            title: string;
            /** @example 📝 */
            emoji?: string | null;
            excerpt?: string | null;
            /**
             * Format: date-time
             * @example 2026-09-06T12:00:00+00:00
             */
            publishedAt?: string | null;
            tags: components["schemas"]["TagSummary"][];
            /** @description 書き手。旧ブログの記事なら null（/posts/{slug} で公開される） */
            author?: components["schemas"]["UserSummary"] | null;
        };
        PaginatedArchivedPosts: {
            items: components["schemas"]["ArchivedPostSummary"][];
            /**
             * @description 全件数
             * @example 42
             */
            total: number;
            page: number;
            perPage: number;
            totalPages: number;
        };
        ArchivedPostDetail: {
            id: number;
            slug: string;
            title: string;
            /** @example 📝 */
            emoji?: string | null;
            excerpt?: string | null;
            /** @description Markdown から変換済みの HTML */
            bodyHtml: string;
            /** Format: date-time */
            publishedAt?: string | null;
            /** Format: date-time */
            updatedAt: string;
            tags: components["schemas"]["TagSummary"][];
            /** @description 書き手。旧ブログの記事なら null（/posts/{slug} で公開される） */
            author?: components["schemas"]["UserSummary"] | null;
            /** @description 共有カード用の画像のキー（/uploads/{key} で配信される） */
            ogImageKey?: string | null;
        };
        TagWithCount: {
            /** @example JavaScript */
            name: string;
            /** @example javascript */
            slug: string;
            /**
             * @description 投稿（アーカイブの場合は記事）の件数
             * @example 12
             */
            postCount: number;
        };
        AuthorizationUrl: {
            /** @description Google の同意画面の URL */
            url: string;
            /** @description CSRF 対策の state。Worker が Cookie に控え、コールバックで照合する */
            state: string;
        };
        SessionIssued: {
            /** @description セッショントークン。Worker が HttpOnly Cookie に入れる */
            token: string;
            /** Format: date-time */
            expiresAt: string;
            /** @description handle が未決定なら true（handle 決定画面へ誘導する） */
            needsHandle: boolean;
        };
        UserSummary: {
            /** @example alice */
            handle: string;
            /** @example Alice */
            displayName: string;
            avatarUrl?: string | null;
        };
        BlockedUser: {
            user: components["schemas"]["UserSummary"];
            blockedAt: string;
        };
        RoomSummary: {
            user: components["schemas"]["UserSummary"];
            bio?: string | null;
            companyName?: string | null;
            /**
             * Format: date-time
             * @description 最新の親投稿の日時
             */
            lastPostAt?: string | null;
            /** @description 人気の部屋: 過去24時間のリアクション数＋返信数 / フォロー中: 未読数 */
            count?: number | null;
        };
        ReactionCount: {
            /** @example 👍 */
            emoji: string;
            /** @example 3 */
            count: number;
        };
        TimesPost: {
            /**
             * @description ULID
             * @example 01J8Z3K6W2Q4Y7T9V1B3N5M7P9
             */
            id: string;
            /** @description 返信なら親投稿の ID */
            parentId?: string | null;
            /** @description 退会したユーザーの投稿なら null */
            author?: components["schemas"]["UserSummary"] | null;
            /**
             * @description deleted: 本人が削除 / hidden: 管理者が非表示にしたか、投稿者が停止中。どちらも本文は空
             * @enum {string}
             */
            state: "visible" | "deleted" | "hidden";
            /** @description 変換済みの HTML。state が visible 以外なら空 */
            bodyHtml: string;
            /** @description R2 上の画像のキー。/uploads/{key} で配信される */
            imageKey?: string | null;
            replyCount: number;
            reactionCount: number;
            reactions: components["schemas"]["ReactionCount"][];
            tags: components["schemas"]["TagSummary"][];
            /** Format: date-time */
            lastReplyAt?: string | null;
            /**
             * Format: date-time
             * @description 編集されていれば日時（「編集済み」表示に使う）
             */
            editedAt?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** @description 添付したブログ記事。非公開・削除になったら null */
            article?: components["schemas"]["ArticleCard"] | null;
            /**
             * @description Jev による判定。sensitive: 不適切な可能性があるので折りたたんで出す（state は visible）/ blocked: 不適切なため自動で非表示にした（state は hidden）
             * @enum {string|null}
             */
            moderation: "sensitive" | "blocked" | null;
        };
        PostPage: {
            items: components["schemas"]["TimesPost"][];
            /** @description 次のページを取るときに ?cursor= に渡す。最後のページなら null */
            nextCursor?: string | null;
        };
        Me: {
            id: string;
            /** @description 初回ログイン直後は未決定で null */
            handle?: string | null;
            displayName: string;
            avatarUrl?: string | null;
            bio?: string | null;
            companyName?: string | null;
            companySlug?: string | null;
            /** @enum {string} */
            role: "user" | "admin";
            unreadNotificationCount: number;
        };
        AccountDeleted: {
            /** @description Worker が R2 から消すべき画像のキー */
            imageKeys: string[];
        };
        UploadTicket: {
            /** @description アップロードする本人の ID（ULID） */
            userId: string;
        };
        ViewerReactions: {
            postId: string;
            /** @description 自分が付けた絵文字 */
            emojis: string[];
        };
        ViewerState: {
            reactions: components["schemas"]["ViewerReactions"][];
            /** @description handle を指定したときだけ。その部屋をフォローしているか */
            isFollowing?: boolean | null;
            /**
             * @description 自分がブロックしている handle（画面上で投稿を折りたたむ）
             * @default []
             */
            blockedHandles: string[];
            /**
             * @description handle を指定したときだけ。その人をブロックしているか
             * @default null
             */
            isBlocking: boolean | null;
        };
        NotificationItem: {
            id: string;
            /** @enum {string} */
            type: "reply" | "mention" | "reaction" | "follow";
            actor?: components["schemas"]["UserSummary"] | null;
            /** @description 通知の対象になった投稿（follow では null） */
            postId?: string | null;
            /** @description リンク先のスレッド（親投稿）の ID（follow では null） */
            threadId?: string | null;
            /** @description スレッドの持ち主の handle。/@{handle}/{threadId} に飛ばす */
            threadHandle?: string | null;
            /** @description 投稿の冒頭（プレーンテキスト）。follow では空文字 */
            excerpt: string;
            /** Format: date-time */
            readAt?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        NotificationPage: {
            items: components["schemas"]["NotificationItem"][];
            nextCursor?: string | null;
            unreadCount: number;
        };
        OrgRooms: {
            slug: string;
            /** @description 表示用の会社名（いちばん多い表記） */
            name: string;
            rooms: components["schemas"]["RoomSummary"][];
        };
        Thread: {
            post: components["schemas"]["TimesPost"];
            /** @description 古い順 */
            replies: components["schemas"]["TimesPost"][];
        };
        PostSource: {
            /** @description Markdown 原文 */
            bodyMarkdown: string;
        };
        SearchResult: {
            /** @description handle か表示名が一致した部屋（最大10件。2ページ目以降は空） */
            users: components["schemas"]["UserSummary"][];
            /** @description 本文が一致した親投稿（新しい順） */
            items: components["schemas"]["TimesPost"][];
            nextCursor?: string | null;
        };
        TagPostPage: {
            tag: components["schemas"]["TagSummary"];
            items: components["schemas"]["TimesPost"][];
            nextCursor?: string | null;
        };
        UserProfile: {
            /** @example alice */
            handle: string;
            displayName: string;
            avatarUrl?: string | null;
            bio?: string | null;
            /** @description 自己申告の所属（未認証） */
            companyName?: string | null;
            /** @description /org/{slug} の slug */
            companySlug?: string | null;
            followerCount: number;
            /** @description 利用停止中か。停止中の部屋は投稿を表示しない */
            suspended: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        /** @description 投稿に添付されたブログ記事（公開中のものだけ） */
        ArticleCard: {
            id: number;
            slug: string;
            title: string;
            emoji?: string | null;
            excerpt?: string | null;
            /** @description 書き手。旧ブログの記事なら null（/posts/{slug} で公開される） */
            author?: components["schemas"]["UserSummary"] | null;
        };
        MyArticle: {
            id: number;
            /** @example hello-world */
            slug: string;
            title: string;
            emoji?: string | null;
            /** @description 本文から自動で作る抜粋 */
            excerpt?: string | null;
            /** @enum {string} */
            status: "draft" | "published";
            /** Format: date-time */
            publishedAt?: string | null;
            /** Format: date-time */
            updatedAt: string;
            tags: components["schemas"]["TagSummary"][];
            /** @description 共有カード用の画像のキー（/uploads/{key} で配信される） */
            ogImageKey?: string | null;
            /**
             * Format: date-time
             * @description 管理者が非表示にした日時。非表示の間は本人にしか見えない
             */
            hiddenAt?: string | null;
        };
        MyArticleList: {
            items: components["schemas"]["MyArticle"][];
        };
        ArticleSource: {
            id: number;
            /** @example hello-world */
            slug: string;
            title: string;
            emoji?: string | null;
            /** @description 本文から自動で作る抜粋 */
            excerpt?: string | null;
            /** @enum {string} */
            status: "draft" | "published";
            /** Format: date-time */
            publishedAt?: string | null;
            /** Format: date-time */
            updatedAt: string;
            tags: components["schemas"]["TagSummary"][];
            /** @description Markdown 原文 */
            bodyMd: string;
            /** @description 共有カード用の画像のキー（/uploads/{key} で配信される） */
            ogImageKey?: string | null;
            /**
             * Format: date-time
             * @description 管理者が非表示にした日時。非表示の間は本人にしか見えない
             */
            hiddenAt?: string | null;
        };
        ArticleInput: {
            title: string;
            /** @description URL に使う（英小文字・数字・ハイフン）。空なら自動で付ける */
            slug?: string | null;
            emoji?: string | null;
            bodyMd: string;
            /** @enum {string} */
            status: "draft" | "published";
            /** @default [] */
            tagSlugs: string[];
            /** @default [] */
            newTags: string[];
            /** @description 共有カード用の画像。書き手本人がアップロードしたものしか指定できない */
            ogImageKey?: string | null;
        };
        ArticlePreviewInput: {
            bodyMd: string;
        };
        ArticlePreview: {
            bodyHtml: string;
        };
        ArticleDeleted: {
            /** @description 消えた共有カード画像のキー（web の Worker が KV から消す） */
            imageKey?: string | null;
        };
        AdminArticle: {
            id: number;
            slug: string;
            title: string;
            emoji?: string | null;
            excerpt?: string | null;
            /** @enum {string} */
            status: "draft" | "published";
            /** @description 旧ブログの記事なら null */
            author?: components["schemas"]["AdminUser"] | null;
            /** Format: date-time */
            hiddenAt?: string | null;
            /** Format: date-time */
            publishedAt?: string | null;
            /** Format: date-time */
            updatedAt: string;
        };
        AdminArticlePage: {
            items: components["schemas"]["AdminArticle"][];
            nextCursor?: string | null;
        };
        ModerationBackfill: {
            /** @description 今回判定した件数 */
            processed: number;
            /** @description そのうち自動で非表示にした件数 */
            blocked: number;
            /** @description そのうち折りたたみにした件数 */
            sensitive: number;
            /** @description まだ未判定の件数 */
            remaining: number;
            /** @description Jev の呼び出しに失敗して途中で止めた（クレジット切れなど） */
            stopped: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_api_admin_posts_index: {
        parameters: {
            query?: {
                cursor?: string | null;
                /** @description この人の投稿に絞る */
                handle?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 削除済み以外の全投稿（非表示を含む）を新しい順に */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPostPage"];
                };
            };
        };
    };
    post_api_admin_posts_moderate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 判定した */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModerationBackfill"];
                };
            };
        };
    };
    post_api_admin_posts_hide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 非表示にした */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPost"];
                };
            };
        };
    };
    post_api_admin_posts_unhide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 非表示を解除した */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPost"];
                };
            };
        };
    };
    delete_api_admin_posts_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 削除した */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostDeleted"];
                };
            };
            /** @description 投稿が存在しない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    get_api_admin_users_index: {
        parameters: {
            query?: {
                /** @description handle か表示名の部分一致 */
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ユーザー一覧（新しい順に50件） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"][];
                };
            };
        };
    };
    post_api_admin_users_suspend: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 停止した。全端末からログアウトさせる */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
            /** @description 管理者は停止できない */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    post_api_admin_users_unsuspend: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 停止を解除した */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
        };
    };
    get_api_admin_reports_index: {
        parameters: {
            query?: {
                /** @description open: 未対応（既定） / resolved: 対応済み */
                status?: "open" | "resolved" | null;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 通報の一覧（新しい順） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminReportPage"];
                };
            };
        };
    };
    post_api_admin_reports_dismiss: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 問題なしとして却下した */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminReport"];
                };
            };
            /** @description 通報が存在しない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    get_api_admin_tags_index: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 全タグ（記事が0件のものも含む） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagSummary"][];
                };
            };
        };
    };
    post_api_admin_tags_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagInput"];
            };
        };
        responses: {
            /** @description 作成されたタグ */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagSummary"];
                };
            };
            /** @description 同じ名前か slug のタグが既にある */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_api_archive_posts_index: {
        parameters: {
            query?: {
                /** @description 1 始まりのページ番号 */
                page?: number;
                /** @description 1ページあたりの件数 */
                perPage?: number;
                /** @description タグの slug で絞り込む */
                tag?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 公開済み記事の一覧を新しい順で返す */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedArchivedPosts"];
                };
            };
        };
    };
    get_api_archive_posts_show: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 記事の詳細 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchivedPostDetail"];
                };
            };
            /** @description 記事が存在しないか、公開されていない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    get_api_archive_tags_index: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description アーカイブ記事を持つタグを、記事数の多い順に返す */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagWithCount"][];
                };
            };
        };
    };
    get_api_auth_google_authorize: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 同意画面の URL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorizationUrl"];
                };
            };
            /** @description Google OAuth が未設定 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    post_api_auth_google_callback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OAuthCallbackInput"];
            };
        };
        responses: {
            /** @description ログイン成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionIssued"];
                };
            };
            /** @description 認可コードが無効 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            /** @description アカウントが停止されている */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    post_api_auth_email_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailCredentialsInput"];
            };
        };
        responses: {
            /** @description ログイン成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionIssued"];
                };
            };
            /** @description 入力が不正、またはアドレスが登録済み */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    post_api_auth_email_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailCredentialsInput"];
            };
        };
        responses: {
            /** @description ログイン成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionIssued"];
                };
            };
            /** @description メールアドレスかパスワードが違う */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            /** @description アカウントが停止・退会済み */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            /** @description 入力が不正 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            /** @description 試行回数の上限 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    delete_api_auth_session_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ログアウトした（トークンを無効化した） */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_api_auth_dev_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DevLoginInput"];
            };
        };
        responses: {
            /** @description ログイン成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionIssued"];
                };
            };
            /** @description 開発用ログインが無効 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    put_api_blocks_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ブロックした（既にしていても 204）。お互いのフォローは外す */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description ユーザーが存在しない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    delete_api_blocks_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ブロックを解除した（していなくても 204） */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_api_blocks_index: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ブロック中のユーザー（新しい順） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockedUser"][];
                };
            };
        };
    };
    put_api_follows_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description フォローした（既にしていても 204）。初回だけ相手にフォロー通知が飛ぶ */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description ブロックの関係にある */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            /** @description 部屋が存在しない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    delete_api_follows_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description フォローを外した */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_api_follows_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description その部屋を既読にした（フォローしていなければ何もしない） */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_api_following: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description フォロー中の部屋と未読数（count）。未読の多い順 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomSummary"][];
                };
            };
        };
    };
    get_api_lobby: {
        parameters: {
            query?: {
                /** @description 前のページの nextCursor */
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 全員の親投稿を新しい順に */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostPage"];
                };
            };
        };
    };
    get_api_rooms_popular: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 過去24時間のリアクション数＋返信数（本人以外から）の多い部屋 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomSummary"][];
                };
            };
        };
    };
    get_api_me_show: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 本人の情報と未読通知数 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description 未ログイン */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    put_api_me_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeUpdateInput"];
            };
        };
        responses: {
            /** @description 更新後の本人の情報 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description handle が既に使われている */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            /** @description 入力値が不正 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    delete_api_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 退会した。投稿の本文・画像・リアクション・フォロー・通知を削除し、ログアウトさせる */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountDeleted"];
                };
            };
        };
    };
    post_api_me_uploads: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description アップロードしてよい */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadTicket"];
                };
            };
            /** @description 回数の上限に達した（Retry-After ヘッダー付き） */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    get_api_me_viewer_state: {
        parameters: {
            query?: {
                /** @description カンマ区切りの投稿 ID（100件まで） */
                postIds?: string | null;
                /** @description 指定すると、その人をフォロー・ブロックしているかも返す */
                handle?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 閲覧者ごとの情報 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ViewerState"];
                };
            };
        };
    };
    get_api_notifications_index: {
        parameters: {
            query?: {
                /** @description 前のページの nextCursor */
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 新しい順 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPage"];
                };
            };
        };
    };
    post_api_notifications_read: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description すべて既読にした */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_api_orgs_users: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 同じ会社を自己申告している人の部屋 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgRooms"];
                };
            };
            /** @description 該当する人がいない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    get_api_posts_show: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description スレッド（親投稿と返信） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Thread"];
                };
            };
            /** @description スレッドがない（返信の ID を指定した場合も 404） */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    put_api_posts_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostUpdateInput"];
            };
        };
        responses: {
            /** @description 編集後の投稿 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimesPost"];
                };
            };
            /** @description 自分の投稿ではない */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            /** @description 入力値が不正 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    delete_api_posts_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 削除した（親投稿は返信を残して「削除されました」になる） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostDeleted"];
                };
            };
            /** @description 自分の投稿ではない */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    get_api_posts_source: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 編集用の Markdown 原文（本人のみ） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostSource"];
                };
            };
            /** @description 投稿が存在しないか、自分の投稿ではない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    post_api_posts_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostInput"];
            };
        };
        responses: {
            /** @description 作成された投稿 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimesPost"];
                };
            };
            /** @description 返信先の投稿者にブロックされている */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            /** @description 入力値が不正 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            /** @description 投稿回数の上限に達した（Retry-After ヘッダー付き） */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    put_api_reactions_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 絵文字1つ（URL エンコードする） */
                emoji: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description リアクションを付けた（既に付いていても 204） */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 投稿者にブロックされている */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            /** @description 絵文字として扱えない */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            /** @description 回数の上限に達した */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    delete_api_reactions_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 絵文字1つ（URL エンコードする） */
                emoji: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description リアクションを外した（付いていなくても 204） */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_api_posts_report: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportInput"];
            };
        };
        responses: {
            /** @description 通報した（同じ投稿を通報し直した場合は内容を差し替える） */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 投稿が存在しない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            /** @description 自分の投稿は通報できない */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            /** @description 回数の上限に達した */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    get_api_search: {
        parameters: {
            query: {
                /** @description 検索語。空白で区切るとすべてを含むものに絞る */
                q: string | null;
                /** @description 前のページの nextCursor */
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 検索結果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"];
                };
            };
        };
    };
    get_api_tags_index: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 全タグ（投稿0件も含む）を投稿数の多い順に。投稿時のタグ選択にも使う */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagWithCount"][];
                };
            };
        };
    };
    get_api_tags_posts: {
        parameters: {
            query?: {
                /** @description 前のページの nextCursor */
                cursor?: string | null;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description タグ付きの親投稿を新しい順に */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagPostPage"];
                };
            };
            /** @description タグが存在しない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    get_api_users_show: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 部屋の持ち主のプロフィール */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description 部屋が存在しない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    get_api_users_posts: {
        parameters: {
            query?: {
                /** @description 前のページの nextCursor */
                cursor?: string | null;
            };
            header?: never;
            path: {
                handle: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 部屋の親投稿を新しい順に */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostPage"];
                };
            };
            /** @description 部屋が存在しない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    get_api_users_articles: {
        parameters: {
            query?: {
                /** @description 1 始まりのページ番号 */
                page?: number;
                /** @description 1ページあたりの件数 */
                perPage?: number;
            };
            header?: never;
            path: {
                handle: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description その人の公開済みの記事（新しい順） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedArchivedPosts"];
                };
            };
            /** @description ユーザーがいない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    get_api_users_articles_show: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                handle: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 公開済みの記事 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchivedPostDetail"];
                };
            };
            /** @description 記事がないか非公開 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    get_api_me_articles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 自分の記事（下書きを含む。更新の新しい順） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyArticleList"];
                };
            };
        };
    };
    post_api_me_articles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArticleInput"];
            };
        };
        responses: {
            /** @description 作った記事 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleSource"];
                };
            };
            /** @description 入力値が不正 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    post_api_me_articles_preview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArticlePreviewInput"];
            };
        };
        responses: {
            /** @description 変換した HTML（保存はしない） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticlePreview"];
                };
            };
        };
    };
    get_api_me_articles_show: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 編集用の記事 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleSource"];
                };
            };
            /** @description 記事がないか自分の記事ではない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    put_api_me_articles_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArticleInput"];
            };
        };
        responses: {
            /** @description 保存した記事 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleSource"];
                };
            };
            /** @description 記事がないか自分の記事ではない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            /** @description 入力値が不正 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    delete_api_me_articles_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 削除した */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleDeleted"];
                };
            };
            /** @description 記事がないか自分の記事ではない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    get_api_admin_articles: {
        parameters: {
            query?: {
                /** @description 直前のページの最後の記事 ID */
                cursor?: string;
                /** @description 書き手で絞り込む */
                handle?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 記事（下書き・非表示を含む。新しい順） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminArticlePage"];
                };
            };
        };
    };
    post_api_admin_articles_hide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 非表示にした */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminArticle"];
                };
            };
            /** @description 記事がない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    post_api_admin_articles_unhide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 非表示を解除した */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminArticle"];
                };
            };
            /** @description 記事がない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    delete_api_admin_articles_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 削除した */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleDeleted"];
                };
            };
            /** @description 記事がない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
}
