/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_admin_posts_index"];
        put?: never;
        post: operations["post_api_admin_posts_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/posts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_admin_posts_show"];
        put: operations["put_api_admin_posts_update"];
        post?: never;
        delete: operations["delete_api_admin_posts_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/posts/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_admin_posts_publish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/posts/{id}/unpublish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_admin_posts_unpublish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_admin_preview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_admin_tags_index"];
        put?: never;
        post: operations["post_api_admin_tags_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_posts_index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_posts_show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_tags_index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PostInput: {
            /**
             * @default
             * @example はじめての記事
             */
            title: string;
            /**
             * @default
             * @example hello-world
             */
            slug: string;
            /**
             * null なら既定の絵文字が入る。
             * @description 記事のアイキャッチ絵文字
             * @example 📝
             */
            emoji?: string | null;
            /**
             * @description Markdown 原文
             * @default
             * @example # 見出し
             *
             *     本文。
             */
            bodyMd: string;
            /**
             * null なら本文から自動生成する。
             * @description 未指定なら本文から自動生成される
             */
            excerpt?: string | null;
            /**
             * 付与するタグの slug。既存のタグのみ指定できる。
             *     新しいタグは POST /api/admin/tags で先に作成すること
             *     （日本語のタグ名から slug を機械的に導出できないため）。
             * @default []
             * @example [
             *       "php",
             *       "symfony"
             *     ]
             */
            tagSlugs: string[];
        };
        MarkdownPreviewInput: {
            /**
             * @description プレビューしたい Markdown 原文
             * @default
             * @example # 見出し
             *
             *     本文。
             */
            bodyMd: string;
        };
        TagInput: {
            /**
             * 表示名。日本語も使える。
             * @default
             * @example JavaScript
             */
            name: string;
            /**
             * URL に使う識別子。日本語名から機械的に導出できないため明示的に指定する。
             * @default
             * @example javascript
             */
            slug: string;
        };
        TagSummary: {
            /** @example JavaScript */
            name: string;
            /** @example javascript */
            slug: string;
        };
        PostAdminSummary: {
            id: number;
            slug: string;
            title: string;
            /** @example 📝 */
            emoji?: string | null;
            /**
             * @example draft
             * @enum {string}
             */
            status: "draft" | "published";
            /** Format: date-time */
            publishedAt?: string | null;
            /** Format: date-time */
            updatedAt: string;
            tags: components["schemas"]["TagSummary"][];
        };
        PostAdminDetail: {
            id: number;
            slug: string;
            title: string;
            /** @example 📝 */
            emoji?: string | null;
            /** @description Markdown 原文 */
            bodyMd: string;
            excerpt?: string | null;
            /** @enum {string} */
            status: "draft" | "published";
            /** Format: date-time */
            publishedAt?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            tags: components["schemas"]["TagSummary"][];
        };
        ValidationError: {
            /** @example 入力内容に誤りがあります。 */
            message: string;
            /**
             * @example {
             *       "slug": "slug は必須です。"
             *     }
             */
            errors: {
                [key: string]: string;
            };
        };
        MarkdownPreview: {
            /** @description 変換後の HTML */
            bodyHtml: string;
            /** @description 本文から自動生成した抜粋 */
            excerpt: string;
        };
        PostSummary: {
            id: number;
            /** @example hello-world */
            slug: string;
            title: string;
            /** @example 📝 */
            emoji?: string | null;
            excerpt?: string | null;
            /**
             * Format: date-time
             * @example 2026-09-06T12:00:00+00:00
             */
            publishedAt?: string | null;
            tags: components["schemas"]["TagSummary"][];
        };
        PaginatedPosts: {
            items: components["schemas"]["PostSummary"][];
            /**
             * @description 全件数
             * @example 42
             */
            total: number;
            page: number;
            perPage: number;
            totalPages: number;
        };
        PostDetail: {
            id: number;
            slug: string;
            title: string;
            /** @example 📝 */
            emoji?: string | null;
            excerpt?: string | null;
            /** @description Markdown から変換済みの HTML */
            bodyHtml: string;
            /** Format: date-time */
            publishedAt?: string | null;
            /** Format: date-time */
            updatedAt: string;
            tags: components["schemas"]["TagSummary"][];
        };
        TagWithCount: {
            /** @example JavaScript */
            name: string;
            /** @example javascript */
            slug: string;
            /**
             * @description 公開済み記事の件数
             * @example 12
             */
            postCount: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_api_admin_posts_index: {
        parameters: {
            query?: {
                /** @description 状態で絞り込む */
                status?: "draft" | "published" | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 下書きを含む全記事を更新の新しい順で返す */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostAdminSummary"][];
                };
            };
        };
    };
    post_api_admin_posts_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostInput"];
            };
        };
        responses: {
            /** @description 作成された記事 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostAdminDetail"];
                };
            };
            /** @description slug が既に使われている */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
            /** @description 入力値が不正 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    get_api_admin_posts_show: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 記事 ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 編集用の記事（Markdown 原文を含む） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostAdminDetail"];
                };
            };
            /** @description 記事が存在しない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    put_api_admin_posts_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 記事 ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostInput"];
            };
        };
        responses: {
            /** @description 更新後の記事 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostAdminDetail"];
                };
            };
        };
    };
    delete_api_admin_posts_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 記事 ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 削除完了 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_api_admin_posts_publish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 記事 ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 公開後の記事 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostAdminDetail"];
                };
            };
        };
    };
    post_api_admin_posts_unpublish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 記事 ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 下書きに戻した記事 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostAdminDetail"];
                };
            };
        };
    };
    post_api_admin_preview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkdownPreviewInput"];
            };
        };
        responses: {
            /** @description 保存時と同じ変換結果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarkdownPreview"];
                };
            };
        };
    };
    get_api_admin_tags_index: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 全タグ（記事が0件のものも含む） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagSummary"][];
                };
            };
        };
    };
    post_api_admin_tags_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagInput"];
            };
        };
        responses: {
            /** @description 作成されたタグ */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagSummary"];
                };
            };
            /** @description 同じ名前か slug のタグが既にある */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_api_posts_index: {
        parameters: {
            query?: {
                /** @description 1 始まりのページ番号 */
                page?: number;
                /** @description 1ページあたりの件数 */
                perPage?: number;
                /** @description タグの slug で絞り込む */
                tag?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 公開済み記事の一覧を新しい順で返す */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPosts"];
                };
            };
        };
    };
    get_api_posts_show: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 記事の詳細 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostDetail"];
                };
            };
            /** @description 記事が存在しないか、まだ公開されていない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    get_api_tags_index: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 公開記事を持つタグを、記事数の多い順に返す */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagWithCount"][];
                };
            };
        };
    };
}
